### ISSUE TITLE
3DSecure V2

### ISSUE THREAD

**Issue by schopart** [ekyna/PayumMonetico#2]
Hello, have you planned the migration of the 3DSecure V2 protocol soon?

https://www.monetico-paiement.fr/fr/info/documentations/MoneticoPaiement_GuideMigration3DSecureV2.pdf

**Comment by ekyna** [comment]
Hi. Yes I have to do this before 30 August. Envoyé depuis mon téléphone Orange-------- Message original --------Objet : [ekyna/PayumMonetico] 3DSecure V2 (#2)De : Steeve Chopart À : ekyna/PayumMonetico Cc : Subscribed Hello, have you planned the migration of the 3DSecure V2 protocol soon?
https://www.monetico-paiement.fr/fr/info/documentations/MoneticoPaiement_GuideMigration3DSecureV2.pdf

**Comment by ekyna** [comment]
Fixed with 1570491 (1.5.3)
